/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manageitem;

import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import manageitem.entity.Item;
/**
 *
 * @author pvcanh
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
   public static List<Item> getAllItem() {
//        ActionEvent e
        List<Item> list = new ArrayList<Item>();
        try {
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/manage_item?autoReconnect=true&useSSL=false",
                    "root", "123456");
            PreparedStatement st = (PreparedStatement) connection
                    .prepareStatement("Select * from item");
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                Item item = new Item();
                item.setId(rs.getInt("id"));
                item.setName(rs.getString("name"));
                item.setQuantity(rs.getInt("quantity"));
                item.setPrice(rs.getString("price"));
                item.setNoted(rs.getString("noted"));
                list.add(item);
            }
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        return list;
    }
   
    public void loadForm(){
        DefaultTableModel model = (DefaultTableModel) tblMain.getModel();
        List<Item> listItem = getAllItem();
        System.err.println(listItem);
        String[] data = new String[5];
        for(Item item : listItem){
           data[0] = String.valueOf(item.getId());
           data[1] = item.getName();
           data[2] = item.getPrice();
           data[3] = String.valueOf(item.getQuantity());
           data[4] = item.getNoted();
           model.addRow(data);
        }
        tblMain.setModel(model);
    }
    
    public void clearTable(){
        DefaultTableModel tMOdel = (DefaultTableModel) tblMain.getModel();
        tMOdel.setRowCount(0);
        tblMain.setModel(tMOdel);
    }
    
    
    public MainFrame() {
        initComponents();
        loadForm();
        lbId.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbName = new javax.swing.JTextField();
        lbPrice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lbNoted = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TÊN", "GIÁ", "SỐ LƯỢNG TỒN", "CHÚ THÍCH"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMain);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 670, 340));

        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 110, 40));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 130, 40));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, 100, 40));

        jLabel1.setText("Tên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbNameActionPerformed(evt);
            }
        });
        getContentPane().add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, 40));
        getContentPane().add(lbPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, 40));

        jLabel2.setText("Giá");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        getContentPane().add(lbQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 240, 40));

        jLabel3.setText("Số lượng tồn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        getContentPane().add(lbNoted, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 240, 40));

        jLabel4.setText("Chú thích");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        lbId.setToolTipText("");
        lbId.setEnabled(false);
        getContentPane().add(lbId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String name = lbName.getText();
        String price = lbPrice.getText();
        int quantity = Integer.parseInt(lbQuantity.getText().trim());
        String noted = lbNoted.getText();
        try {
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/manage_item?autoReconnect=true&useSSL=false",
                    "root", "123456");
            Statement st=(Statement) connection.createStatement();  
            // Adding record 
            String query1="INSERT INTO `manage_item`.`item`"
             + " (`name`, `price`, `quantity`, `noted`)"
             + "VALUES('" +name+"','"+price+"',"+quantity+",'"+noted+"')";
            st.executeUpdate(query1);
            connection.close();  
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        clearTable();
        loadForm();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int index = tblMain.getSelectedRow();
        TableModel model = tblMain.getModel();
        int id = Integer.parseInt(lbId.getText());
        String name = lbName.getText();
        String price = lbPrice.getText();
        int quantity = Integer.parseInt(lbQuantity.getText());
        String noted = lbNoted.getText();
        try {
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/manage_item?autoReconnect=true&useSSL=false",
                    "root", "123456");
            Statement st=(Statement) connection.createStatement();  
            String query1="UPDATE `manage_item`.`item`"
             + "SET `name` = '"+name+"', `price` = '"+price+"', `quantity` = "+quantity+", `noted` = '"+noted+"'"
             + " WHERE `id` = " + id;
            System.out.print(query1);
            st.executeUpdate(query1);
            connection.close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        clearTable();
        loadForm();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int index = tblMain.getSelectedRow();
        TableModel model = tblMain.getModel();
        String id = model.getValueAt(index,0).toString();
        try {
            Connection connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/manage_item?autoReconnect=true&useSSL=false",
                    "root", "123456");
            Statement st=(Statement) connection.createStatement();  
            String query1="DELETE FROM `manage_item`.`item` WHERE `id` = " + id;
            System.out.print(query1);
            st.execute(query1);
            connection.close();
        } catch (SQLException sqlException) {
            sqlException.printStackTrace();
        }
        clearTable();
        loadForm();        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        int index = tblMain.getSelectedRow();
        TableModel model = tblMain.getModel();
        String id = model.getValueAt(index,0).toString();
        String name = model.getValueAt(index, 1).toString();
        String price = model.getValueAt(index, 2).toString();
        String quantity = model.getValueAt(index, 3).toString();
        String noted = model.getValueAt(index, 4).toString();
        lbId.setText(id);
        lbName.setText(name);
        lbPrice.setText(price);
        lbQuantity.setText(quantity);
        lbNoted.setText(noted);
    }//GEN-LAST:event_tblMainMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lbId;
    private javax.swing.JTextField lbName;
    private javax.swing.JTextField lbNoted;
    private javax.swing.JTextField lbPrice;
    private javax.swing.JTextField lbQuantity;
    private javax.swing.JTable tblMain;
    // End of variables declaration//GEN-END:variables
}
